#!/bin/sh

# --- Apps ---
super + Return
  $TERMINAL
super + r
  rofi -show drun

# --- Nodes and desktops ---
super + {_,shift +} {1-9,0}
  bspc {desktop -f,node -d} '{1-9,10}' '--follow'
super + ctrl + {1-9,0}
  bspc node -d '{1-9,10}'
super + {_,shift +}{h,l,j,k}
  bspc node -{f,s} {west,east,north,south}
super + {_,shift +} Tab
  bspc node -f {next,prev}.local
super + {_,shift +} c
  bspc node -{c,k}
super + f
  bspc node -t "~"fullscreen
super + space
  bspc node -t "~"{floating,tiled}
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}
super + control + {Left,Right,Up,Down}
	bspc node -z {left -20 0,right 20 0,top 0 -20,bottom 0 20}
super + alt + {Left,Right,Up,Down}
	bspc node -z {left 20 0,right -20 0,top 0 20,bottom 0 -20}

# --- General ---
super + shift + Escape
  bspc quit
super + shift + r
  killall sxhkd && sxhkd

# --- Media keys ---
XF86MonBrightnessDown
  light -U  5
XF86MonBrightnessUp
  light -A 5
XF86AudioLowerVolume
  pactl -- set-sink-volume 0 -5%
XF86AudioRaiseVolume
  pactl -- set-sink-volume 0 +5%
XF86AudioMute
  pactl list sinks | grep -q Mute:.no && pactl set-sink-mute 0 1 || pactl set-sink-mute 0 0
XF86AudioMicMute
  pactl set-source-mute 1 toggle
